* Bootstrapping
** Initialize package.el
We need to initialize package.el before req-package, and we also need it at
compile time to bootstrap req-package.
#+BEGIN_SRC emacs-lisp
  (eval-and-compile
    (require 'package)
    (package-initialize)
    (setq package-enable-at-startup nil))
#+END_SRC
** Put customizations in their own file
Installing packages modifies custom variables, so we need to move the custom
file very early in initialization.
#+BEGIN_SRC emacs-lisp
  (eval-and-compile
    (setq custom-file (locate-user-emacs-file "custom.el"))
    (load custom-file 'no-error))
#+END_SRC
** Add package archives
We need MELPA to install req-package, so we set these up at compile time.
#+BEGIN_SRC emacs-lisp
  (eval-and-compile
    (setq package-archives
          '(("gnu" . "https://elpa.gnu.org/packages/")
            ("melpa" . "https://melpa.org/packages/")
            ("marmalade" . "https://marmalade-repo.org/packages/"))))
#+END_SRC
** Bootstrap req-package
Install req-package if needed and require it.
#+BEGIN_SRC emacs-lisp
  (eval-and-compile
    (unless (package-installed-p 'req-package)
      (package-refresh-contents)
      (package-install 'req-package))
    (require 'req-package))
#+END_SRC
* Theme
Set Solarized as the default theme.
#+BEGIN_SRC emacs-lisp
  (req-package solarized-theme
    :loader :elpa
    :config
    (load-theme 'solarized-light 'no-confirm))
#+END_SRC
* Native UI
Disable some pieces of the native UI.
#+BEGIN_SRC emacs-lisp
  (req-package scroll-bar
    :loader :built-in
    :defer t
    :config
    (scroll-bar-mode -1))

  (req-package tool-bar
    :loader :built-in
    :defer t
    :config
    (tool-bar-mode -1))
#+END_SRC
* Splash screen
#+BEGIN_SRC emacs-lisp
  (setq inhibit-startup-screen t)
#+END_SRC
* Window layout
Automatically lay windows out using golden-ratio.
#+BEGIN_SRC emacs-lisp
  (req-package golden-ratio
    :loader :elpa
    :diminish golden-ratio-mode
    :config
    (golden-ratio-mode))
#+END_SRC
* Smartparens
Enable strict mode for Smartparens everywhere, and set up Paredit-like
keybindings.
#+BEGIN_SRC emacs-lisp
  (req-package smartparens-config
    :force
    :ensure smartparens
    :demand
    :bind (:map smartparens-mode-map
                ("M-s" . sp-splice-sexp)
                ("M-<up>" . sp-splice-sexp-killing-backward)
                ("M-<down>" . sp-splice-sexp-killing-forward)
                ("M-r" . sp-raise-sexp)
                ("C-<right>" . sp-forward-slurp-sexp)
                ("C-<left>" . sp-forward-barf-sexp)
                ("C-M-<left>" . sp-backward-slurp-sexp)
                ("C-M-<right>" . sp-backward-barf-sexp)
                ("M-S" . sp-split-sexp)
                ("M-J" . sp-join-sexp)
                ("M-R" . sp-rewrap-sexp))
    :config
    (smartparens-global-strict-mode))
#+END_SRC
* Language server protocol
Add a mode for integrating with language servers to provide
completion, go-to-definition, etc.
#+BEGIN_SRC emacs-lisp
  (req-package lsp-mode
    :loader :elpa
    :defer t)
#+END_SRC
* Rust
** Major mode
Set up rust-mode and have it automatically format files using rustfmt.
#+BEGIN_SRC emacs-lisp
  (req-package rust-mode
    :loader :elpa
    :defer t
    :config
    (setq rust-format-on-save t))
#+END_SRC
** Rust language server integration
Load rust-specific pieces of lsp-mode and load it alongside rust-mode.
#+BEGIN_SRC emacs-lisp
  (req-package lsp-rust
    :require lsp-mode rust-mode
    :loader :elpa
    :defer t
    :init
    (add-hook 'rust-mode-hook
              (lambda ()
                ;; Somewhat unfortunately, there doesn't seem to be a
                ;; way to autoload lsp-rust, so we have to require it
                ;; manually before we call lsp-mode.
                (require 'lsp-rust)
                (lsp-mode))))
#+END_SRC
* SLIME
Set up the Superior Lisp Interaction Mode for Emacs, using SBCL and
Quicklisp.
#+BEGIN_SRC emacs-lisp
  (req-package slime
    :loader :elpa
    :defer t
    :config
    (load (expand-file-name "~/.local/lib/quicklisp/slime-helper.el"))
    (setq inferior-lisp-program "sbcl")
    (setq slime-contribs '(slime-fancy)))
#+END_SRC
* Version control
Set up Magit.
#+BEGIN_SRC emacs-lisp
  (req-package magit
    :loader :elpa
    :defer t)
#+END_SRC
* Backups
I've never once used an Emacs backup file, and I make regular
full-system backups, so I think we can turn them off.
#+BEGIN_SRC emacs-lisp
  (setq make-backup-files nil)
#+END_SRC
* Overwrite selection
Cause the selection to be overwritten by editing commands.
#+BEGIN_SRC emacs-lisp
  (req-package delsel
    :loader :built-in
    :config
    (delete-selection-mode))
#+END_SRC
* Coq
Proof General isn't set up as a package, so we have to have it
installed locally. We use it to load .v files as Coq.
#+BEGIN_SRC emacs-lisp
  (req-package proof-site
    :loader :path
    :load-path "lisp/PG/generic/"
    :mode ("\\.v\\'" . coq-mode))
#+END_SRC
* Haskell
Set up haskell-mode with REPL support.
#+BEGIN_SRC emacs-lisp
  (req-package haskell-mode
    :loader :elpa
    :defer t
    :config
    (add-hook 'haskell-mode-hook #'interactive-haskell-mode))
#+END_SRC
* Finalization
Execute our req-package statements according to the dependency graph.
#+BEGIN_SRC emacs-lisp
  (req-package-finish)
#+END_SRC
